<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Task_12.Models\Task_12.Models.csproj" />
    <ProjectReference Include="..\Task_12.Repositories\Task_12.Repositories.csproj" />
  </ItemGroup>

</Project>
