USE [master]
GO

CREATE DATABASE SelfFinance
GO

USE SelfFinance
GO

CREATE TABLE IncomeCategories(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] VARCHAR(225) NOT NULL
)
GO

CREATE TABLE Incomes(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Date] DATE NOT NULL,
	IncomeCategoryId UNIQUEIDENTIFIER,
	Amount DECIMAL NOT NULL,
	FOREIGN KEY (IncomeCategoryId) REFERENCES IncomeCategories(Id) ON DELETE SET NULL
)

CREATE TABLE ExpenseCategories(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] VARCHAR(225)	NOT NULL
)
GO

CREATE TABLE Expenses(
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Date] DATE NOT NULL,
	ExpenseCategoryId UNIQUEIDENTIFIER,
	Amount DECIMAL NOT NULL,
	FOREIGN KEY (ExpenseCategoryId) REFERENCES ExpenseCategories(Id) ON DELETE SET NULL
)